# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-20 13:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apiget', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='data',
            new_name='Data',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='name',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='information',
            name='Class',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
