# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiget', '0002_auto_20161020_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='HoleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=2)),
                ('targetType', models.CharField(max_length=10)),
                ('scanType', models.CharField(max_length=2)),
                ('description', models.TextField()),
                ('level', models.CharField(max_length=2)),
                ('createTime', models.BigIntegerField()),
                ('checkResult', models.BooleanField()),
                ('updateStatus', models.CharField(max_length=2)),
                ('productName', models.CharField(max_length=50)),
                ('h_id', models.CharField(max_length=20)),
                ('targets', models.TextField()),
                ('offset', models.IntegerField()),
            ],
        ),
    ]
