# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 08:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiget', '0003_holeinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holeinfo',
            name='offset',
        ),
    ]
