# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-04 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiget', '0004_remove_holeinfo_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='holeinfo',
            name='groupName',
            field=models.CharField(default='other', max_length=10),
            preserve_default=False,
        ),
    ]
