# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiget', '0006_testinfos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testinfos',
            name='allow_tests',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='testinfos',
            name='allow_tests_pass',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='testinfos',
            name='bugs_escape',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='testinfos',
            name='bugs_escape_noduty',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='testinfos',
            name='bugs_escape_p1',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='testinfos',
            name='bugs_escape_p1_noduty',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='testinfos',
            name='bugs_found',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='testinfos',
            name='bugs_found_function',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='testinfos',
            name='bugs_found_function_p1',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='testinfos',
            name='bugs_found_p1',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='testinfos',
            name='bugs_other',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='testinfos',
            name='bugs_other_p1',
            field=models.CharField(max_length=8),
        ),
    ]
