# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-15 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiget', '0007_auto_20161115_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=10)),
                ('group', models.CharField(max_length=10)),
                ('grade1', models.FloatField()),
                ('grade2', models.FloatField()),
                ('feedback', models.TextField()),
                ('feedback_done', models.CharField(max_length=2)),
                ('need_machine', models.CharField(max_length=2)),
                ('need_person', models.CharField(max_length=2)),
                ('bug_qua', models.CharField(max_length=2)),
                ('suggest', models.CharField(max_length=2)),
                ('good', models.CharField(max_length=2)),
                ('process', models.CharField(max_length=2)),
                ('chat', models.CharField(max_length=2)),
                ('escape1', models.CharField(max_length=2)),
            ],
        ),
    ]
