# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiget', '0010_marketshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketshare',
            name='market',
            field=models.CharField(default='Worldwide', max_length=10),
            preserve_default=False,
        ),
    ]
