# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiget', '0011_marketshare_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketshare',
            name='productname',
        ),
        migrations.AddField(
            model_name='marketshare',
            name='value',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
