# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiget', '0012_auto_20161206_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketshare',
            name='productname',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
