# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-09 03:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiget', '0013_marketshare_productname'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketshare',
            name='remarks',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
