# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiget', '0016_auto_20161219_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsshare',
            name='datetype',
            field=models.CharField(default='D', max_length=2),
            preserve_default=False,
        ),
    ]
