# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-23 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiget', '0018_auto_20161220_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='holeinfo',
            name='vulType',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
