# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-27 06:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiget', '0020_auto_20161223_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='holeinfo',
            name='title',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
