# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-28 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiget', '0021_holeinfo_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holeinfo',
            name='checkResult',
            field=models.CharField(max_length=2),
        ),
    ]
